# another file6
FROM openjdk:22-oracle

USER root

WORKDIR /app

COPY . .

RUN  mv target/spring-boot-hello-world-0.0.1-SNAPSHOT.jar /run/app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/run/app.jar"]
