FROM openjdk:22-oracle

RUN useradd -m sandeep

WORKDIR /home/sandeep/app

COPY . .

RUN chown -R sandeep:sandeep .

USER sandeep

RUN  mv target/spring-boot-hello-world-0.0.1-SNAPSHOT.jar /run/app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/run/app.jar"]
