FROM cloudsihmar/maven:spring

RUN useradd -ms /bin/sh sandeep

WORKDIR /home/sandeep/app

COPY . .

RUN chown -R sandeep:sandeep .

USER sandeep

RUN  mvn package && mv target/spring-boot-hello-world-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8080
EXPOSE 8081
EXPOSE 8082

ENTRYPOINT ["java", "-jar", "app.jar"]
